# docker-compose.yml


services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./api:/var/www
    ports:
      - "9000:9000"  # PHP-FPM port; nginx will proxy to this container
    env_file:
      - ./api/.env

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"   # Expose port 80 to host port 8000
    volumes:
      - ./api:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d  # Custom Nginx config files
    depends_on:
      - app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nextjs-client
    container_name: nextjs-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - app
    command: yarn dev